/*
  # Add Test Servers

  1. New Data
    - 50 test servers with varied configurations
    - Different platforms (Java, Bedrock, Cross-platform)
    - Various gamemodes and countries
    - Realistic player counts and vote numbers
    - Mix of approved and pending servers

  2. Test Data Features
    - Diverse server names and descriptions
    - Different IP addresses and ports
    - Various Minecraft versions supported
    - Mix of whitelist and non-whitelist servers
    - Sample banner URLs and social links
*/

-- Insert test servers with realistic data
INSERT INTO servers (
  name, ip, java_port, bedrock_port, query_port, platform, gamemode, 
  additional_gamemodes, min_version, max_version, country, website, 
  discord, youtube, description, banner_url, has_whitelist, 
  votifier_enabled, status, featured, votes, players_online, 
  players_max, uptime, user_id
) VALUES 
-- Java Servers
('HyperCraft Network', 'play.hypercraft.net', 25565, NULL, 25565, 'java', 'survival', 'pvp, economy, towny', '1.16', '1.21', 'United States', 'https://hypercraft.net', 'https://discord.gg/hypercraft', 'https://youtube.com/hypercraft', 'Welcome to HyperCraft Network! Experience the ultimate survival gameplay with custom plugins, amazing builds, and a friendly community. Join thousands of players in our expansive world featuring custom biomes, dungeons, and epic quests. Our server offers a balanced economy, player shops, and regular events. Whether you''re a builder, explorer, or fighter, there''s something for everyone here!', 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg', false, true, 'approved', true, 2847, 156, 200, 99.2, (SELECT id FROM user_profiles LIMIT 1)),

('SkyBlock Paradise', 'skyblock.paradise.com', 25565, NULL, 25565, 'java', 'skyblock', 'economy, minigames', '1.18', '1.21', 'Germany', 'https://skyblockparadise.com', 'https://discord.gg/skyblockparadise', NULL, 'The ultimate SkyBlock experience awaits! Start with nothing but a tree and a chest, then build your way to greatness. Our custom SkyBlock features unique challenges, custom items, and an advanced economy system. Trade with other players, complete daily quests, and unlock new islands as you progress. With over 100 custom achievements and regular updates, your SkyBlock journey never ends!', NULL, false, false, 'approved', false, 1923, 89, 150, 98.7, (SELECT id FROM user_profiles LIMIT 1)),

('PvP Arena Masters', 'pvp.arena-masters.net', 25565, NULL, 25565, 'java', 'pvp', 'kitpvp, factions, uhc', '1.8', '1.20', 'United Kingdom', NULL, 'https://discord.gg/pvparena', 'https://youtube.com/pvparena', 'Dominate the battlefield in PvP Arena Masters! Our server features multiple PvP gamemodes including KitPvP, Factions, and UHC tournaments. With custom enchantments, balanced kits, and anti-cheat protection, every fight is fair and exciting. Join our weekly tournaments for amazing prizes and climb the leaderboards to become the ultimate PvP champion. New players get starter kits and protection!', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg', false, true, 'approved', false, 1456, 67, 100, 97.8, (SELECT id FROM user_profiles LIMIT 1)),

('Creative Builders Hub', 'creative.builders-hub.org', 25565, NULL, 25565, 'java', 'creative', 'build battle, parkour', '1.17', '1.21', 'Canada', 'https://buildershub.org', 'https://discord.gg/buildershub', NULL, 'Unleash your creativity at Creative Builders Hub! Our server provides unlimited resources, WorldEdit tools, and massive plots for your building projects. Participate in weekly build competitions, showcase your creations in our gallery, and learn from master builders. We offer tutorials, building challenges, and a supportive community that celebrates creativity. From pixel art to massive structures, build your dreams here!', NULL, true, false, 'approved', false, 892, 34, 80, 99.5, (SELECT id FROM user_profiles LIMIT 1)),

('Prison Break Elite', 'prison.elite-mc.com', 25565, NULL, 25565, 'java', 'prison', 'economy, pvp', '1.16', '1.21', 'Australia', 'https://prisonelite.com', 'https://discord.gg/prisonelite', 'https://youtube.com/prisonelite', 'Start your journey from the lowest prison rank and work your way to freedom! Prison Break Elite features a unique ranking system, custom mines, and an advanced economy. Mine valuable resources, sell them for profit, and upgrade your gear. With PvP zones, gang wars, and special events, there''s always action. Can you escape and become the richest player on the server?', 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg', false, true, 'approved', false, 1678, 78, 120, 98.3, (SELECT id FROM user_profiles LIMIT 1)),

-- Bedrock Servers
('Bedrock Adventures', 'bedrock.adventures.net', NULL, 19132, 25565, 'bedrock', 'survival', 'creative, minigames', '1.19', '1.21', 'United States', 'https://bedrockadventures.net', 'https://discord.gg/bedrockadv', NULL, 'The premier Bedrock Edition server for mobile and console players! Experience smooth gameplay optimized for touch controls and console interfaces. Our survival world features custom terrain generation, mobile-friendly interfaces, and cross-platform compatibility. Play with friends across all devices including Xbox, PlayStation, Nintendo Switch, and mobile. Regular events and updates keep the adventure fresh!', NULL, false, false, 'approved', false, 1234, 45, 100, 99.1, (SELECT id FROM user_profiles LIMIT 1)),

('Pocket Edition Pro', 'pe.pro-servers.com', NULL, 19132, 25565, 'bedrock', 'minigames', 'pvp, parkour, build battle', '1.18', '1.21', 'Netherlands', NULL, 'https://discord.gg/pepro', 'https://youtube.com/pepro', 'Mobile gaming at its finest! Pocket Edition Pro offers lag-free minigames designed specifically for mobile devices. Our touch-optimized interfaces make playing easy and fun. Choose from dozens of minigames including SkyWars, BedWars, and custom arcade games. With cloud save support and cross-device progression, you can play anywhere, anytime. Perfect for gaming on the go!', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg', false, false, 'approved', false, 987, 67, 80, 97.9, (SELECT id FROM user_profiles LIMIT 1)),

-- Cross-platform Servers
('Unity Network', 'play.unity-network.com', 25565, 19132, 25565, 'crossplatform', 'survival', 'economy, towny, creative', '1.19', '1.21', 'Germany', 'https://unity-network.com', 'https://discord.gg/unitynetwork', NULL, 'Where Java and Bedrock players unite! Unity Network brings together players from all platforms in one amazing survival experience. Our cross-platform technology ensures seamless gameplay whether you''re on PC, mobile, or console. Build towns with friends, participate in server-wide events, and enjoy features designed for all platforms. True unity in Minecraft!', NULL, false, true, 'approved', true, 3456, 189, 250, 99.8, (SELECT id FROM user_profiles LIMIT 1)),

('CrossPlay Central', 'crossplay.central-mc.net', 25565, 19132, 25565, 'crossplatform', 'factions', 'pvp, economy, mcmmo', '1.16', '1.21', 'France', 'https://crossplaycentral.net', 'https://discord.gg/crossplay', 'https://youtube.com/crossplay', 'The ultimate cross-platform factions experience! Battle players from Java and Bedrock editions in epic faction wars. Our balanced gameplay ensures fair competition across all platforms. Build your base, recruit members, and dominate the battlefield. With custom enchantments, faction perks, and regular war events, the action never stops. Cross-platform voice chat included!', 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg', false, true, 'approved', false, 2134, 98, 180, 98.5, (SELECT id FROM user_profiles LIMIT 1)),

-- More Java Servers
('Towny Legends', 'towny.legends-mc.org', 25565, NULL, 25565, 'java', 'towny', 'economy, survival', '1.18', '1.21', 'Sweden', 'https://townylegends.org', 'https://discord.gg/townylegends', NULL, 'Build your town and create a lasting legacy! Towny Legends offers the classic town-building experience with modern features. Claim land, invite residents, and grow your settlement into a thriving city. Our balanced economy system rewards both builders and traders. Form nations, engage in diplomacy, and participate in server-wide events. Your town''s story starts here!', NULL, false, false, 'approved', false, 1567, 56, 120, 99.0, (SELECT id FROM user_profiles LIMIT 1)),

('Anarchy Chaos', 'anarchy.chaos-mc.net', 25565, NULL, 25565, 'java', 'anarchy', NULL, '1.12', '1.21', 'Russia', NULL, 'https://discord.gg/anarchychaos', NULL, 'No rules, no limits, pure chaos! Anarchy Chaos is a true anarchy server where anything goes. Hack, grief, build, or destroy - the choice is yours. Our world has been running since 2019 with no resets, creating a rich history of player conflicts and alliances. With no staff interference and minimal plugins, experience Minecraft in its rawest form. Survival of the fittest!', NULL, false, false, 'approved', false, 2789, 123, 150, 96.2, (SELECT id FROM user_profiles LIMIT 1)),

('Vanilla Plus', 'vanilla.plus-mc.com', 25565, NULL, 25565, 'java', 'vanilla', 'survival', '1.20', '1.21', 'Japan', 'https://vanillaplus.com', NULL, NULL, 'Pure vanilla Minecraft with quality-of-life improvements! Vanilla Plus maintains the authentic Minecraft experience while adding small enhancements like one-player sleep, mob heads, and armor stands with arms. Our community values fair play, collaboration, and the simple joy of vanilla Minecraft. No pay-to-win, no overpowered plugins, just pure Minecraft fun with friends!', NULL, true, false, 'approved', false, 1345, 67, 100, 99.7, (SELECT id FROM user_profiles LIMIT 1)),

('Economy Empire', 'economy.empire-mc.net', 25565, NULL, 25565, 'java', 'economy', 'survival, towny', '1.19', '1.21', 'Brazil', 'https://economyempire.net', 'https://discord.gg/economyempire', NULL, 'Build your business empire in our advanced economy server! Start with basic jobs like mining and farming, then work your way up to owning shops, companies, and even entire industries. Our realistic economy features stock markets, banks, and complex supply chains. Trade with other players, invest wisely, and become the richest player on the server. Your business acumen determines your success!', NULL, false, true, 'approved', false, 1789, 89, 140, 98.8, (SELECT id FROM user_profiles LIMIT 1)),

('Hardcore Survival', 'hardcore.survival-mc.org', 25565, NULL, 25565, 'java', 'hardcore', 'survival', '1.18', '1.21', 'Norway', NULL, 'https://discord.gg/hardcoresurvival', 'https://youtube.com/hardcoresurvival', 'Think you can survive the ultimate challenge? Hardcore Survival features permanent death, increased mob difficulty, and limited resources. One life is all you get - make it count! Our world is designed to test even the most experienced players. With custom mobs, dangerous weather events, and scarce resources, every decision matters. Only the strongest survive in this unforgiving world!', 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg', true, false, 'approved', false, 876, 23, 50, 97.1, (SELECT id FROM user_profiles LIMIT 1)),

('Pixelmon World', 'pixelmon.world-mc.com', 25565, NULL, 25565, 'java', 'pixelmon', 'economy, adventure', '1.16', '1.16', 'Mexico', 'https://pixelmonworld.com', 'https://discord.gg/pixelmonworld', NULL, 'Catch ''em all in the world of Pixelmon! Our server features the complete Pixelmon experience with custom regions, gym leaders, and Elite Four challenges. Train your Pokemon, battle other trainers, and explore vast custom-built regions. With regular tournaments, shiny hunting events, and a thriving economy, your Pokemon journey never ends. Gotta catch ''em all!', NULL, false, false, 'approved', false, 1456, 78, 120, 98.4, (SELECT id FROM user_profiles LIMIT 1)),

-- More diverse servers
('Lifesteal Legends', 'lifesteal.legends-mc.net', 25565, NULL, 25565, 'java', 'lifesteal', 'pvp, survival', '1.19', '1.21', 'Poland', NULL, 'https://discord.gg/lifesteallegends', NULL, 'Gain hearts by defeating other players in this intense lifesteal server! Start with 10 hearts and fight your way to 20 by eliminating opponents. But be careful - losing fights means losing hearts permanently. Our balanced combat system ensures fair fights while maintaining the thrill of high-stakes PvP. Custom items, enchantments, and abilities add depth to every battle!', NULL, false, true, 'approved', false, 1678, 45, 80, 97.6, (SELECT id FROM user_profiles LIMIT 1)),

('MCMMO Masters', 'mcmmo.masters-mc.org', 25565, NULL, 25565, 'java', 'mcmmo', 'survival, economy', '1.18', '1.21', 'Finland', 'https://mcmmomasters.org', 'https://discord.gg/mcmmomasters', NULL, 'Level up your skills in the ultimate MCMMO experience! Our server features all MCMMO skills with custom abilities, party systems, and skill competitions. Train your mining, woodcutting, combat, and other skills to unlock powerful abilities. Compete in skill tournaments, join parties with friends, and become the most skilled player on the server. Your dedication determines your power!', NULL, false, false, 'approved', false, 1234, 67, 100, 98.9, (SELECT id FROM user_profiles LIMIT 1)),

('Roleplay Realms', 'roleplay.realms-mc.com', 25565, NULL, 25565, 'java', 'roleplay', 'economy, towny', '1.19', '1.21', 'United Kingdom', 'https://roleplayrealms.com', 'https://discord.gg/roleplayrealms', 'https://youtube.com/roleplayrealms', 'Immerse yourself in our medieval fantasy roleplay world! Create your character, choose a profession, and live in our carefully crafted kingdoms. Our server features custom races, classes, and an in-depth lore system. Participate in kingdom politics, trade with merchants, and embark on epic quests. With dedicated staff and active players, every day brings new adventures in our living, breathing world!', 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg', true, false, 'approved', false, 987, 34, 60, 99.3, (SELECT id FROM user_profiles LIMIT 1)),

('Parkour Paradise', 'parkour.paradise-mc.net', 25565, NULL, 25565, 'java', 'parkour', 'minigames, creative', '1.17', '1.21', 'South Korea', NULL, 'https://discord.gg/parkourparadise', NULL, 'Jump, climb, and race through hundreds of custom parkour courses! Parkour Paradise features courses for all skill levels, from beginner-friendly tutorials to expert-level challenges that will test your limits. Compete for the fastest times, unlock new courses, and show off your skills. With new courses added weekly and special themed events, there''s always a new challenge waiting!', NULL, false, false, 'approved', false, 756, 23, 50, 98.1, (SELECT id FROM user_profiles LIMIT 1)),

('Bedwars Central', 'bedwars.central-mc.org', 25565, NULL, 25565, 'java', 'bedwars', 'skywars, uhc', '1.8', '1.20', 'Spain', 'https://bedwarscentral.org', 'https://discord.gg/bedwarscentral', 'https://youtube.com/bedwarscentral', 'Protect your bed and destroy your enemies in epic Bedwars battles! Our server features multiple Bedwars modes including Solo, Doubles, and 4v4 team battles. With custom maps, balanced gameplay, and anti-cheat protection, every game is competitive and fair. Climb the ranked ladder, unlock cosmetics, and prove you''re the ultimate Bedwars champion!', NULL, false, false, 'approved', false, 2345, 134, 200, 98.7, (SELECT id FROM user_profiles LIMIT 1)),

-- More Bedrock servers
('Mobile Craft', 'mobile.craft-pe.com', NULL, 19132, 25565, 'bedrock', 'survival', 'creative, economy', '1.19', '1.21', 'India', NULL, 'https://discord.gg/mobilecraft', NULL, 'The best Minecraft experience for mobile devices! Mobile Craft is optimized for touch controls with intuitive interfaces and smooth gameplay. Our survival world features mobile-friendly building tools, simplified menus, and lag-free performance. Perfect for playing during commutes or relaxing at home. Join our growing community of mobile Minecraft enthusiasts!', NULL, false, false, 'approved', false, 1123, 56, 100, 98.2, (SELECT id FROM user_profiles LIMIT 1)),

('Console Kings', 'console.kings-mc.net', NULL, 19132, 25565, 'bedrock', 'pvp', 'minigames, factions', '1.18', '1.21', 'United States', 'https://consolekings.net', 'https://discord.gg/consolekings', NULL, 'Dominate the battlefield from your couch! Console Kings is designed for Xbox, PlayStation, and Nintendo Switch players. Our PvP modes feature controller-optimized combat, split-screen support, and console-exclusive features. Battle friends locally or compete online in our ranked tournaments. The ultimate console Minecraft experience awaits!', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg', false, false, 'approved', false, 1567, 78, 120, 97.8, (SELECT id FROM user_profiles LIMIT 1)),

-- More Cross-platform servers
('Global Gaming', 'global.gaming-mc.org', 25565, 19132, 25565, 'crossplatform', 'economy', 'survival, towny, creative', '1.19', '1.21', 'Singapore', 'https://globalgaming.org', 'https://discord.gg/globalgaming', 'https://youtube.com/globalgaming', 'Connecting players worldwide across all platforms! Global Gaming features seamless cross-platform gameplay where Java and Bedrock players can interact naturally. Our economy system works perfectly across all devices, and our custom features are designed to work on every platform. Join players from around the world in our truly global Minecraft community!', NULL, false, true, 'approved', true, 4567, 234, 300, 99.5, (SELECT id FROM user_profiles LIMIT 1)),

('Universal Minecraft', 'universal.mc-server.net', 25565, 19132, 25565, 'crossplatform', 'minigames', 'pvp, parkour, build battle', '1.18', '1.21', 'Canada', 'https://universalmc.net', 'https://discord.gg/universalmc', NULL, 'One server, all platforms, endless fun! Universal Minecraft offers the largest collection of cross-platform minigames. Whether you''re on Java, Bedrock, mobile, or console, you can compete in the same games with the same features. Our advanced cross-platform technology ensures fair gameplay for everyone. Join the universal gaming revolution!', 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg', false, false, 'approved', false, 2890, 167, 250, 98.9, (SELECT id FROM user_profiles LIMIT 1)),

-- Additional diverse servers
('Skyblock Infinity', 'skyblock.infinity-mc.com', 25565, NULL, 25565, 'java', 'skyblock', 'economy, minigames', '1.19', '1.21', 'Netherlands', NULL, 'https://discord.gg/skyblockinfinity', NULL, 'Infinite possibilities in the sky! Skyblock Infinity features unlimited custom islands, advanced automation systems, and a complex economy. Start with a basic island and expand it into a massive sky empire. With custom crops, animals, and machines, automate your way to success. Regular island competitions and leaderboards keep the competition fierce!', NULL, false, false, 'approved', false, 1890, 89, 150, 98.6, (SELECT id FROM user_profiles LIMIT 1)),

('Factions War', 'factions.war-mc.net', 25565, NULL, 25565, 'java', 'factions', 'pvp, economy', '1.16', '1.20', 'Turkey', 'https://factionswar.net', 'https://discord.gg/factionswar', 'https://youtube.com/factionswar', 'Wage war in the ultimate factions server! Build your base, recruit loyal members, and conquer enemy territories. Our faction system features advanced claiming, custom cannons, and epic siege warfare. With weekly faction events, bounty systems, and alliance mechanics, political strategy is just as important as combat skills. Lead your faction to victory!', NULL, false, true, 'approved', false, 2456, 123, 180, 97.9, (SELECT id FROM user_profiles LIMIT 1)),

('Creative Unlimited', 'creative.unlimited-mc.org', 25565, NULL, 25565, 'java', 'creative', 'build battle, parkour', '1.18', '1.21', 'Italy', 'https://creativeunlimited.org', 'https://discord.gg/creativeunlimited', NULL, 'Unlimited creativity, unlimited possibilities! Creative Unlimited provides massive plots, WorldEdit access, and all blocks for your building projects. Our server features plot competitions, building tutorials, and a showcase system for your best creations. Whether you''re building pixel art, modern architecture, or fantasy castles, our community supports and celebrates all forms of creativity!', NULL, false, false, 'approved', false, 1123, 45, 80, 99.4, (SELECT id FROM user_profiles LIMIT 1)),

('Hunger Games Arena', 'hungergames.arena-mc.com', 25565, NULL, 25565, 'java', 'hunger games', 'pvp, survival', '1.8', '1.19', 'Czech Republic', NULL, 'https://discord.gg/hungergames', NULL, 'May the odds be ever in your favor! Our Hunger Games server features authentic arena battles with custom maps, sponsor systems, and realistic survival mechanics. Scavenge for supplies, form alliances, and outlast 23 other tributes to claim victory. With rotating arenas and special themed games, every match offers a unique challenge. Only one can survive!', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg', false, false, 'approved', false, 1678, 67, 100, 98.3, (SELECT id FROM user_profiles LIMIT 1)),

('Murder Mystery Manor', 'murder.mystery-mc.net', 25565, NULL, 25565, 'java', 'murder mystery', 'minigames', '1.16', '1.21', 'Belgium', 'https://murdermystery.net', 'https://discord.gg/murdermystery', NULL, 'Solve crimes or commit them in our thrilling murder mystery games! Each round, one player becomes the murderer while others must survive and identify the killer. With custom maps, unique roles, and special abilities, every game is a new mystery to solve. Use your detective skills, work with other innocents, and catch the murderer before it''s too late!', NULL, false, false, 'approved', false, 987, 34, 60, 98.7, (SELECT id FROM user_profiles LIMIT 1)),

('Build Battle Pro', 'buildbattle.pro-mc.org', 25565, NULL, 25565, 'java', 'build battle', 'creative, minigames', '1.17', '1.21', 'Denmark', NULL, 'https://discord.gg/buildbattlepro', NULL, 'Show off your building skills in fast-paced competitions! Build Battle Pro features timed building contests where creativity meets speed. With themes ranging from simple objects to complex scenes, every round tests different aspects of your building ability. Vote on other players'' builds, climb the leaderboards, and unlock special building materials. The ultimate test of creative skill!', NULL, false, false, 'approved', false, 1234, 56, 80, 98.8, (SELECT id FROM user_profiles LIMIT 1)),

('Spleef Champions', 'spleef.champions-mc.com', 25565, NULL, 25565, 'java', 'spleef', 'minigames, pvp', '1.8', '1.20', 'Ireland', NULL, 'https://discord.gg/spleefchampions', NULL, 'Dig your way to victory in classic Spleef battles! Spleef Champions features multiple arena types, power-ups, and tournament modes. Break blocks beneath your opponents'' feet while avoiding falling yourself. With custom tools, special abilities, and team modes, we''ve revolutionized the classic Spleef experience. Fast-paced action and strategic thinking required!', NULL, false, false, 'approved', false, 876, 23, 50, 99.1, (SELECT id FROM user_profiles LIMIT 1)),

('The Bridge Warriors', 'bridge.warriors-mc.net', 25565, NULL, 25565, 'java', 'the bridge', 'pvp, minigames', '1.8', '1.19', 'Portugal', 'https://bridgewarriors.net', 'https://discord.gg/bridgewarriors', NULL, 'Cross the bridge and score goals in this unique PvP gamemode! The Bridge combines combat skills with objective-based gameplay. Fight your way across the bridge while defending your own goal. With custom kits, power-ups, and team strategies, every match is intense and competitive. Master the bridge and become a true warrior!', NULL, false, false, 'approved', false, 1345, 67, 100, 98.2, (SELECT id FROM user_profiles LIMIT 1)),

('TNT Run Masters', 'tntrun.masters-mc.org', 25565, NULL, 25565, 'java', 'tnt run', 'minigames', '1.16', '1.21', 'Greece', NULL, 'https://discord.gg/tntrunmasters', NULL, 'Run for your life as the floor disappears beneath you! TNT Run Masters features multiple arena types, power-ups, and survival challenges. Stay moving as TNT blocks disappear, creating an ever-shrinking battlefield. With custom arenas, special abilities, and team modes, we''ve taken TNT Run to the next level. Last player standing wins!', NULL, false, false, 'approved', false, 765, 34, 60, 98.5, (SELECT id FROM user_profiles LIMIT 1)),

('UHC Champions', 'uhc.champions-mc.net', 25565, NULL, 25565, 'java', 'uhc', 'pvp, survival', '1.8', '1.19', 'Romania', 'https://uhcchampions.net', 'https://discord.gg/uhcchampions', NULL, 'Ultra Hardcore survival at its finest! UHC Champions features classic UHC gameplay with no natural regeneration, golden apple crafting, and PvP after shrinking borders. Our matches feature custom scenarios, team modes, and spectator systems. With experienced hosts and fair gameplay, every UHC match is competitive and exciting. Prove your survival skills!', 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg', false, false, 'approved', false, 1456, 45, 80, 97.7, (SELECT id FROM user_profiles LIMIT 1)),

-- More Bedrock servers
('PE Adventures', 'pe.adventures-mc.com', NULL, 19132, 25565, 'bedrock', 'adventure', 'survival, economy', '1.19', '1.21', 'Thailand', NULL, 'https://discord.gg/peadventures', NULL, 'Epic adventures designed for Pocket Edition! PE Adventures features custom adventure maps, quest systems, and mobile-optimized gameplay. Explore vast custom worlds, complete challenging quests, and unlock new areas as you progress. Our touch-friendly interfaces and optimized performance ensure smooth gameplay on any mobile device. Adventure awaits in your pocket!', NULL, false, false, 'approved', false, 1234, 67, 100, 98.4, (SELECT id FROM user_profiles LIMIT 1)),

('Bedrock Builders', 'bedrock.builders-mc.net', NULL, 19132, 25565, 'bedrock', 'creative', 'build battle, survival', '1.18', '1.21', 'Malaysia', 'https://bedrockbuilders.net', 'https://discord.gg/bedrockbuilders', NULL, 'Building made easy on Bedrock Edition! Bedrock Builders provides creative plots, building competitions, and tutorials specifically designed for Bedrock players. Our mobile-friendly building tools and simplified interfaces make creating amazing structures easier than ever. Join our community of talented builders and showcase your creativity across all Bedrock platforms!', NULL, false, false, 'approved', false, 987, 45, 80, 98.9, (SELECT id FROM user_profiles LIMIT 1)),

-- Pending servers for testing admin panel
('New Server Test', 'new.test-server.com', 25565, NULL, 25565, 'java', 'survival', NULL, '1.20', '1.21', 'United States', NULL, NULL, NULL, 'This is a test server that is pending approval. It features basic survival gameplay with a small community. The server is new and looking to grow its player base. We offer a friendly environment for new and experienced players alike. Our staff team is dedicated to providing a great experience for all players. Join us and help build our community from the ground up! We have basic plugins for protection and economy. The world is fresh and ready for exploration. Come check us out and see what we have to offer. We are always looking for feedback to improve our server and make it the best it can be for our players.', NULL, false, false, 'pending', false, 0, 0, 50, 0, (SELECT id FROM user_profiles LIMIT 1)),

('Another Pending', 'pending.server-test.org', 25565, NULL, 25565, 'java', 'creative', NULL, '1.19', '1.21', 'Germany', 'https://pendingserver.org', NULL, NULL, 'Another test server awaiting approval from the admin team. This creative server offers unlimited building possibilities with WorldEdit access and custom plots. Our community focuses on collaborative building projects and creative competitions. We have experienced builders who can help newcomers learn advanced building techniques. The server features regular building contests with prizes for the most creative designs. Our plot system allows for both individual and team projects. We also offer building tutorials and workshops for players who want to improve their skills. Join our creative community today!', NULL, true, false, 'pending', false, 0, 0, 40, 0, (SELECT id FROM user_profiles LIMIT 1)),

('Test Bedrock Server', 'test.bedrock-pe.com', NULL, 19132, 25565, 'bedrock', 'minigames', 'pvp', '1.18', '1.21', 'Canada', NULL, 'https://discord.gg/testbedrock', NULL, 'A Bedrock Edition test server currently under review. We offer various minigames optimized for mobile and console play. Our games include SkyWars, BedWars, and custom arcade modes designed specifically for touch controls and controller input. The server features cross-platform voice chat and party systems. We are committed to providing lag-free gameplay across all Bedrock platforms. Our anti-cheat system ensures fair play for all users. Regular updates and new game modes keep the experience fresh and exciting. We welcome players of all skill levels and provide tutorials for new players to learn the games quickly and easily.', NULL, false, false, 'pending', false, 0, 0, 60, 0, (SELECT id FROM user_profiles LIMIT 1)),

-- More approved servers with different characteristics
('Zombie Apocalypse', 'zombie.apocalypse-mc.net', 25565, NULL, 25565, 'java', 'zombies', 'survival, pvp', '1.16', '1.21', 'South Africa', NULL, 'https://discord.gg/zombieapocalypse', 'https://youtube.com/zombieapocalypse', 'Survive the zombie apocalypse in this intense survival server! Zombie Apocalypse features custom zombie AI, realistic survival mechanics, and base-building systems. Scavenge for supplies, fortify your base, and work with other survivors to stay alive. With custom weapons, medical systems, and dynamic zombie hordes, every day is a fight for survival. Can you survive the apocalypse?', NULL, false, false, 'approved', false, 1789, 89, 120, 97.4, (SELECT id FROM user_profiles LIMIT 1)),

('Capture The Flag', 'ctf.battle-mc.org', 25565, NULL, 25565, 'java', 'capture the flag', 'pvp, minigames', '1.8', '1.20', 'Argentina', 'https://ctfbattle.org', 'https://discord.gg/ctfbattle', NULL, 'Strategic team-based combat in epic CTF battles! Capture The Flag features large-scale team battles with custom maps, classes, and objectives. Work with your team to capture the enemy flag while defending your own. With multiple game modes, custom kits, and balanced gameplay, every match requires teamwork and strategy. Join the battle and lead your team to victory!', 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg', false, false, 'approved', false, 1345, 78, 120, 98.1, (SELECT id FROM user_profiles LIMIT 1)),

('Walls PvP', 'walls.pvp-mc.com', 25565, NULL, 25565, 'java', 'walls', 'pvp, survival', '1.8', '1.16', 'Chile', NULL, 'https://discord.gg/wallspvp', NULL, 'Prepare, build, and fight in the classic Walls gamemode! Teams start separated by massive walls with time to gather resources and prepare for battle. When the walls fall, epic PvP combat begins! Our server features balanced teams, custom maps, and fair resource distribution. Strategy during preparation is just as important as combat skills. Build your defenses and prepare for war!', NULL, false, false, 'approved', false, 1123, 56, 100, 98.6, (SELECT id FROM user_profiles LIMIT 1)),

('Hide and Seek Fun', 'hideandseek.fun-mc.net', 25565, NULL, 25565, 'java', 'hide and seek', 'minigames', '1.16', '1.21', 'New Zealand', NULL, 'https://discord.gg/hideandseekfun', NULL, 'The ultimate hide and seek experience! Hide and Seek Fun features custom maps, disguise systems, and special abilities for both hiders and seekers. Transform into blocks, use special items, and find the perfect hiding spots. With dozens of unique maps and regular updates, every game offers new hiding opportunities. Can you stay hidden until time runs out?', NULL, false, false, 'approved', false, 876, 34, 60, 99.0, (SELECT id FROM user_profiles LIMIT 1)),

('Duels Arena', 'duels.arena-mc.org', 25565, NULL, 25565, 'java', 'duels', 'pvp, minigames', '1.8', '1.20', 'Austria', 'https://duelsarena.org', 'https://discord.gg/duelsarena', NULL, 'Face off in intense 1v1 combat! Duels Arena features multiple duel types including sword, bow, and potion PvP. Our ranking system matches you with players of similar skill levels for fair and competitive fights. With custom kits, arena selection, and spectator modes, every duel is exciting to play and watch. Climb the leaderboards and prove your PvP mastery!', NULL, false, false, 'approved', false, 1567, 67, 100, 98.3, (SELECT id FROM user_profiles LIMIT 1)),

('Earth SMP', 'earth.smp-mc.com', 25565, NULL, 25565, 'java', 'earth', 'survival, economy, towny', '1.19', '1.21', 'Switzerland', 'https://earthsmp.com', 'https://discord.gg/earthsmp', 'https://youtube.com/earthsmp', 'Build civilizations on a 1:1000 scale Earth map! Earth SMP features a realistic Earth terrain where you can claim real-world locations and build nations. Our geopolitical system allows for diplomacy, trade, and warfare between nations. With realistic biomes, climate systems, and resource distribution, strategy and geography matter. Create your empire and shape world history!', NULL, false, true, 'approved', false, 2890, 145, 200, 99.1, (SELECT id FROM user_profiles LIMIT 1)),

('Eggwars Elite', 'eggwars.elite-mc.net', 25565, NULL, 25565, 'java', 'eggwars', 'pvp, minigames', '1.8', '1.19', 'Croatia', NULL, 'https://discord.gg/eggwarselite', NULL, 'Protect your egg and destroy your enemies! Eggwars Elite features team-based combat with resource collection and strategic gameplay. Gather resources from generators, buy equipment, and attack enemy teams while protecting your own egg. With custom maps, balanced gameplay, and anti-cheat protection, every match is competitive and fair. Teamwork and strategy lead to victory!', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg', false, false, 'approved', false, 1789, 89, 140, 98.4, (SELECT id FROM user_profiles LIMIT 1)),

('Lucky Block Madness', 'luckyblock.madness-mc.org', 25565, NULL, 25565, 'java', 'lucky block', 'pvp, minigames', '1.8', '1.16', 'Slovenia', 'https://luckyblockmadness.org', 'https://discord.gg/luckyblockmadness', NULL, 'Break lucky blocks and hope for the best! Lucky Block Madness features chaotic battles where breaking lucky blocks can give you amazing items or terrible curses. With hundreds of custom lucky block outcomes, every break is a surprise. Battle other players with your lucky loot in our custom arenas. Luck and skill combine for unpredictable fun!', NULL, false, false, 'approved', false, 1234, 67, 100, 97.8, (SELECT id FROM user_profiles LIMIT 1)),

('OneBlock Survival', 'oneblock.survival-mc.com', 25565, NULL, 25565, 'java', 'oneblock', 'survival, economy', '1.19', '1.21', 'Latvia', NULL, 'https://discord.gg/oneblocksurvival', NULL, 'Start with one block and build an empire! OneBlock Survival features the popular OneBlock gamemode where breaking your single block generates new blocks and items. Progress through different phases, unlock new biomes, and face unique challenges. With custom phases, rare drops, and an economy system, your OneBlock island can become a thriving base. How far can you progress?', NULL, false, false, 'approved', false, 1456, 56, 80, 98.7, (SELECT id FROM user_profiles LIMIT 1)),

('Paintball Wars', 'paintball.wars-mc.net', 25565, NULL, 25565, 'java', 'paintball', 'pvp, minigames', '1.16', '1.21', 'Estonia', NULL, 'https://discord.gg/paintballwars', NULL, 'Colorful combat in our paintball arenas! Paintball Wars features team-based paintball battles with custom maps and game modes. Use paintball guns to eliminate opponents while capturing objectives. With multiple arena types, team strategies, and special power-ups, every match is action-packed. No violence, just colorful fun and competitive gameplay!', NULL, false, false, 'approved', false, 987, 45, 80, 98.9, (SELECT id FROM user_profiles LIMIT 1)),

('Quake Craft', 'quake.craft-mc.org', 25565, NULL, 25565, 'java', 'quake', 'pvp, minigames', '1.8', '1.19', 'Lithuania', 'https://quakecraft.org', 'https://discord.gg/quakecraft', NULL, 'Fast-paced FPS action in Minecraft! Quake Craft brings first-person shooter gameplay to Minecraft with railguns, power-ups, and arena combat. Our custom physics engine provides smooth movement and precise aiming. With multiple arena types, game modes, and weapon upgrades, every match is intense and skill-based. Quick reflexes and accurate aim determine the winner!', NULL, false, false, 'approved', false, 1123, 34, 60, 98.2, (SELECT id FROM user_profiles LIMIT 1)),

-- More Cross-platform servers
('Family Friendly Fun', 'family.friendly-mc.net', 25565, 19132, 25565, 'crossplatform', 'survival', 'creative, minigames', '1.19', '1.21', 'Australia', 'https://familyfriendly.net', 'https://discord.gg/familyfriendly', NULL, 'A safe and fun environment for players of all ages! Family Friendly Fun features moderated chat, grief protection, and family-oriented gameplay. Parents and children can play together safely with our strict community guidelines and active moderation. Our survival world includes educational elements, building challenges, and cooperative gameplay. Cross-platform support means the whole family can play together regardless of device!', NULL, false, false, 'approved', false, 1678, 89, 150, 99.6, (SELECT id FROM user_profiles LIMIT 1)),

('Student Craft', 'student.craft-edu.org', 25565, 19132, 25565, 'crossplatform', 'creative', 'survival, economy', '1.18', '1.21', 'United States', 'https://studentcraft.org', 'https://discord.gg/studentcraft', NULL, 'Educational Minecraft for students and teachers! Student Craft provides a learning environment where education meets gaming. Build historical monuments, explore scientific concepts, and collaborate on educational projects. Our server features curriculum-aligned activities, teacher tools, and safe multiplayer environments. Perfect for schools, homeschooling, and educational gaming. Learning has never been this fun!', 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg', true, false, 'approved', false, 1345, 67, 120, 99.8, (SELECT id FROM user_profiles LIMIT 1)),

('Retro Gaming', 'retro.gaming-mc.com', 25565, 19132, 25565, 'crossplatform', 'minigames', 'arcade, pvp', '1.16', '1.21', 'Japan', 'https://retrogaming.com', 'https://discord.gg/retrogaming', 'https://youtube.com/retrogaming', 'Classic arcade games recreated in Minecraft! Retro Gaming features pixel-perfect recreations of classic arcade games like Pac-Man, Tetris, and Space Invaders. Our custom resource packs and game mechanics provide authentic retro gaming experiences. With high score leaderboards, tournament modes, and nostalgic soundtracks, relive the golden age of gaming in Minecraft!', NULL, false, false, 'approved', false, 1890, 78, 120, 98.5, (SELECT id FROM user_profiles LIMIT 1)),

-- Additional unique servers
('Cops and Robbers', 'cops.robbers-mc.net', 25565, NULL, 25565, 'java', 'cops and robbers', 'pvp, roleplay', '1.16', '1.21', 'Israel', NULL, 'https://discord.gg/copsrobbers', NULL, 'Choose your side in this thrilling cops and robbers gamemode! Play as a police officer maintaining law and order, or as a criminal pulling off heists and escaping justice. Our custom maps feature realistic cities, prisons, and escape routes. With custom items, vehicles, and role-specific abilities, every round tells a different story. Will justice prevail or will crime pay?', NULL, false, false, 'approved', false, 1456, 67, 100, 98.0, (SELECT id FROM user_profiles LIMIT 1)),

('FTB Modded', 'ftb.modded-mc.org', 25565, NULL, 25565, 'java', 'ftb', 'survival, economy', '1.16', '1.16', 'Germany', 'https://ftbmodded.org', 'https://discord.gg/ftbmodded', NULL, 'Experience Minecraft with hundreds of mods! FTB Modded features the Feed The Beast modpack with technology, magic, and exploration mods. Build complex machines, master magical arts, and explore new dimensions. Our server provides a stable modded experience with helpful community members and detailed guides. From simple automation to complex factories, the possibilities are endless!', NULL, false, false, 'approved', false, 1234, 45, 80, 98.8, (SELECT id FROM user_profiles LIMIT 1)),

('HCF Hardcore', 'hcf.hardcore-mc.net', 25565, NULL, 25565, 'java', 'hcf', 'pvp, factions', '1.8', '1.8', 'United States', 'https://hcfhardcore.net', 'https://discord.gg/hcfhardcore', NULL, 'Hardcore Factions with deathbans and intense PvP! HCF Hardcore features the classic HCF experience with deathbans, faction claiming, and kit-based PvP. When you die, you''re banned for a set time, making every life precious. Our balanced kits, custom enchantments, and strategic gameplay create intense faction warfare. Only the strongest factions survive in this hardcore environment!', 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg', false, true, 'approved', false, 2345, 123, 150, 96.8, (SELECT id FROM user_profiles LIMIT 1)),

('KitPvP Arena', 'kitpvp.arena-mc.com', 25565, NULL, 25565, 'java', 'kitpvp', 'pvp', '1.8', '1.19', 'Brazil', NULL, 'https://discord.gg/kitpvparena', NULL, 'Choose your kit and dominate the arena! KitPvP Arena features dozens of custom kits with unique abilities and playstyles. From archer kits with special arrows to tank kits with heavy armor, find the kit that suits your combat style. Our balanced arena design ensures fair fights, while our ranking system matches you with appropriate opponents. Master all kits and become the ultimate warrior!', NULL, false, false, 'approved', false, 1678, 89, 120, 97.9, (SELECT id FROM user_profiles LIMIT 1)),

-- More diverse servers
('Vanilla Hardcore', 'vanilla.hardcore-mc.org', 25565, NULL, 25565, 'java', 'hardcore', 'survival', '1.20', '1.21', 'Norway', NULL, 'https://discord.gg/vanillahardcore', NULL, 'Pure vanilla hardcore survival with permanent death! Vanilla Hardcore offers the ultimate survival challenge with no respawning and minimal plugins. Our world features natural terrain generation, authentic mob spawning, and classic Minecraft mechanics. With a tight-knit community and memorial system for fallen players, every life tells a story. How long can you survive in the hardcore world?', NULL, true, false, 'approved', false, 987, 23, 40, 98.9, (SELECT id FROM user_profiles LIMIT 1)),

('Speed Builders', 'speed.builders-mc.net', 25565, NULL, 25565, 'java', 'build battle', 'minigames, creative', '1.16', '1.21', 'Denmark', NULL, 'https://discord.gg/speedbuilders', NULL, 'Build fast, build accurate! Speed Builders challenges players to recreate structures as quickly and accurately as possible. With time pressure and complex builds, only the fastest and most skilled builders succeed. Our scoring system rewards both speed and accuracy, creating intense competition. Practice mode helps you improve, while ranked matches test your skills against the best builders!', NULL, false, false, 'approved', false, 1234, 56, 80, 98.7, (SELECT id FROM user_profiles LIMIT 1)),

('Survival Games', 'survival.games-mc.com', 25565, NULL, 25565, 'java', 'hunger games', 'pvp, survival', '1.8', '1.19', 'Ireland', 'https://survivalgames.com', 'https://discord.gg/survivalgames', 'https://youtube.com/survivalgames', 'Battle royale in custom-built arenas! Survival Games features authentic Hunger Games gameplay with custom maps, sponsor systems, and realistic survival mechanics. Gather supplies, form alliances, and outlast other tributes in epic battles. Our rotating map system and special event games keep the experience fresh. May the odds be ever in your favor!', NULL, false, false, 'approved', false, 1890, 78, 120, 98.1, (SELECT id FROM user_profiles LIMIT 1)),

('Block Hunt', 'blockhunt.games-mc.org', 25565, NULL, 25565, 'java', 'hide and seek', 'minigames', '1.16', '1.21', 'Bulgaria', NULL, 'https://discord.gg/blockhunt', NULL, 'Transform into blocks and hide from the hunters! Block Hunt features the popular prop hunt gamemode where players disguise as blocks while hunters try to find them. With custom maps, special abilities, and time pressure, every round is tense and exciting. Use your environment wisely, stay still when needed, and outlast the hunters to win!', NULL, false, false, 'approved', false, 1123, 45, 80, 98.4, (SELECT id FROM user_profiles LIMIT 1)),

('Racing Circuit', 'racing.circuit-mc.net', 25565, NULL, 25565, 'java', 'minigames', 'racing, parkour', '1.17', '1.21', 'Slovakia', 'https://racingcircuit.net', 'https://discord.gg/racingcircuit', NULL, 'High-speed racing action in Minecraft! Racing Circuit features custom vehicles, race tracks, and competitive racing gameplay. Choose from cars, boats, and planes to compete in various racing modes. Our physics engine provides realistic vehicle handling while maintaining Minecraft''s charm. With time trials, tournaments, and custom tracks, every race is a new challenge!', 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg', false, false, 'approved', false, 1345, 67, 100, 98.6, (SELECT id FROM user_profiles LIMIT 1)),

('Wizard PvP', 'wizard.pvp-mc.com', 25565, NULL, 25565, 'java', 'pvp', 'magic, minigames', '1.16', '1.21', 'Hungary', NULL, 'https://discord.gg/wizardpvp', 'https://youtube.com/wizardpvp', 'Master the magical arts in spell-based combat! Wizard PvP features custom magic systems, spell crafting, and arena battles. Learn different schools of magic, combine spells for powerful effects, and duel other wizards in mystical arenas. Our balanced magic system ensures skill matters more than luck. Become the most powerful wizard in the realm!', NULL, false, false, 'approved', false, 1567, 78, 120, 98.2, (SELECT id FROM user_profiles LIMIT 1)),

-- Final batch of servers
('Skyblock Legends', 'skyblock.legends-mc.net', 25565, NULL, 25565, 'java', 'skyblock', 'economy, minigames', '1.18', '1.21', 'Ukraine', 'https://skyblocklegends.net', 'https://discord.gg/skyblocklegends', NULL, 'Become a legend in the ultimate skyblock experience! Skyblock Legends features custom islands, advanced automation, and a complex progression system. Start with a basic island and expand it into a massive sky empire. With custom crops, animals, and machines, automate your way to the top. Compete in island competitions and become a true skyblock legend!', NULL, false, false, 'approved', false, 1789, 89, 140, 98.8, (SELECT id FROM user_profiles LIMIT 1)),

('Prison Escape', 'prison.escape-mc.org', 25565, NULL, 25565, 'java', 'prison', 'economy, pvp', '1.17', '1.21', 'Vietnam', NULL, 'https://discord.gg/prisonescape', NULL, 'Work your way from prisoner to freedom! Prison Escape features a unique ranking system where players mine their way through prison ranks. Each rank unlocks new areas, better tools, and more opportunities. With custom mines, prison jobs, and an economy system, there are many paths to freedom. PvP zones add danger and excitement to your escape journey!', NULL, false, true, 'approved', false, 1456, 67, 100, 98.3, (SELECT id FROM user_profiles LIMIT 1)),

('Creative Masters', 'creative.masters-mc.com', 25565, NULL, 25565, 'java', 'creative', 'build battle, parkour', '1.19', '1.21', 'South Korea', 'https://creativemasters.com', 'https://discord.gg/creativemasters', NULL, 'Where master builders are born! Creative Masters provides unlimited resources, advanced building tools, and a supportive community for serious builders. Our plot system accommodates projects of any size, while our tutorial system helps new builders learn advanced techniques. With regular competitions, featured builds, and collaboration opportunities, your building skills will reach new heights!', 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg', false, false, 'approved', false, 1234, 45, 80, 99.2, (SELECT id FROM user_profiles LIMIT 1)),

('Minigame Central', 'minigame.central-mc.net', 25565, 19132, 25565, 'crossplatform', 'minigames', 'pvp, parkour, build battle', '1.18', '1.21', 'Singapore', 'https://minigamecentral.net', 'https://discord.gg/minigamecentral', 'https://youtube.com/minigamecentral', 'The largest collection of cross-platform minigames! Minigame Central features over 50 different games playable across Java and Bedrock editions. From classic games like SkyWars and BedWars to unique custom games, there''s something for everyone. Our cross-platform technology ensures fair gameplay regardless of your device. Join thousands of players in endless minigame fun!', NULL, false, false, 'approved', true, 3789, 189, 250, 99.3, (SELECT id FROM user_profiles LIMIT 1)),

('Adventure Quest', 'adventure.quest-mc.org', 25565, NULL, 25565, 'java', 'adventure', 'rpg, survival', '1.19', '1.21', 'Czech Republic', 'https://adventurequest.org', 'https://discord.gg/adventurequest', NULL, 'Embark on epic quests in our custom adventure world! Adventure Quest features hand-crafted dungeons, custom NPCs, and an immersive storyline. Level up your character, learn new skills, and discover powerful artifacts. Our quest system provides hundreds of hours of content with branching storylines and multiple endings. Your choices shape the world around you!', NULL, false, false, 'approved', false, 1567, 78, 120, 98.6, (SELECT id FROM user_profiles LIMIT 1)),

('Faction Warfare', 'faction.warfare-mc.net', 25565, NULL, 25565, 'java', 'factions', 'pvp, economy, mcmmo', '1.16', '1.20', 'Poland', 'https://factionwarfare.net', 'https://discord.gg/factionwarfare', NULL, 'Epic faction battles with custom warfare systems! Faction Warfare features advanced claiming, siege weapons, and strategic combat. Build impenetrable bases, recruit loyal members, and wage war against enemy factions. Our custom plugins add depth to faction gameplay with supply lines, spy systems, and diplomatic options. Lead your faction to dominance through cunning and strength!', 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg', false, true, 'approved', false, 2234, 112, 180, 97.7, (SELECT id FROM user_profiles LIMIT 1)),

('Towny Nations', 'towny.nations-mc.com', 25565, NULL, 25565, 'java', 'towny', 'economy, survival, diplomacy', '1.18', '1.21', 'Sweden', 'https://townynations.com', 'https://discord.gg/townynations', 'https://youtube.com/townynations', 'Build towns, form nations, and shape history! Towny Nations features an advanced political system where towns can form nations, engage in diplomacy, and participate in server-wide conflicts. Our economy system supports trade between towns, while our war system allows for strategic conflicts. Create your legacy as a town mayor or nation leader!', NULL, false, false, 'approved', false, 1890, 89, 150, 99.0, (SELECT id FROM user_profiles LIMIT 1)),

('Vanilla Survival', 'vanilla.survival-mc.org', 25565, NULL, 25565, 'java', 'vanilla', 'survival', '1.20', '1.21', 'Finland', NULL, 'https://discord.gg/vanillasurvival', NULL, 'Pure vanilla Minecraft survival experience! Vanilla Survival maintains the authentic Minecraft experience with minimal plugins and natural gameplay. Our community values collaboration, fair play, and the simple joy of vanilla Minecraft. With grief protection and a friendly community, you can focus on building, exploring, and enjoying Minecraft as it was meant to be played!', NULL, false, false, 'approved', false, 1345, 67, 100, 99.5, (SELECT id FROM user_profiles LIMIT 1)),

('Economy Plus', 'economy.plus-mc.net', 25565, NULL, 25565, 'java', 'economy', 'survival, towny, jobs', '1.19', '1.21', 'Belgium', 'https://economyplus.net', 'https://discord.gg/economyplus', NULL, 'Advanced economy gameplay with realistic market systems! Economy Plus features a complex economy with supply and demand, stock markets, and business ownership. Start with basic jobs, save money, and invest in businesses or real estate. Our realistic economic simulation includes inflation, market crashes, and economic cycles. Build your financial empire and become the richest player!', NULL, false, true, 'approved', false, 1678, 78, 120, 98.7, (SELECT id FROM user_profiles LIMIT 1)),

('Survival Hardcore', 'survival.hardcore-mc.com', 25565, NULL, 25565, 'java', 'survival', 'hardcore, economy', '1.18', '1.21', 'Switzerland', NULL, 'https://discord.gg/survivalhardcore', NULL, 'Hardcore survival with increased difficulty! Survival Hardcore features enhanced mob AI, limited resources, and realistic survival mechanics. Food spoils over time, weather affects gameplay, and mobs are more dangerous than ever. Our hardcore survival experience tests even veteran players. With permadeath events and hardcore challenges, only the most skilled survive!', NULL, true, false, 'approved', false, 1123, 34, 60, 97.5, (SELECT id FROM user_profiles LIMIT 1)),

('PvE Adventure', 'pve.adventure-mc.org', 25565, NULL, 25565, 'java', 'pve', 'adventure, survival', '1.19', '1.21', 'Croatia', 'https://pveadventure.org', 'https://discord.gg/pveadventure', 'https://youtube.com/pveadventure', 'Player vs Environment challenges and adventures! PvE Adventure features custom dungeons, boss battles, and cooperative gameplay. Team up with other players to tackle challenging PvE content including raid bosses, puzzle dungeons, and survival challenges. Our custom mobs and boss mechanics provide unique PvE experiences not found in vanilla Minecraft. Cooperation and strategy lead to victory!', NULL, false, false, 'approved', false, 1456, 67, 100, 98.8, (SELECT id FROM user_profiles LIMIT 1)),

('RPG Realms', 'rpg.realms-mc.net', 25565, NULL, 25565, 'java', 'rpg', 'adventure, economy', '1.18', '1.21', 'Romania', 'https://rpgrealms.net', 'https://discord.gg/rpgrealms', NULL, 'Immersive RPG experience with classes, quests, and progression! RPG Realms features a complete RPG system with character classes, skill trees, and epic questlines. Choose your path as a warrior, mage, or rogue, then embark on adventures across multiple realms. With custom items, abilities, and storylines, your character''s journey is unique. Level up, gear up, and become a legend!', 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg', false, false, 'approved', false, 1789, 89, 140, 98.4, (SELECT id FROM user_profiles LIMIT 1)),

('Skywars Pro', 'skywars.pro-mc.com', 25565, NULL, 25565, 'java', 'skywars', 'pvp, minigames', '1.8', '1.20', 'Serbia', NULL, 'https://discord.gg/skywarspro', NULL, 'Master the skies in competitive Skywars battles! Skywars Pro features balanced islands, custom kits, and ranked gameplay. Start on your island, gather resources, and eliminate other players while avoiding the void. Our anti-cheat system ensures fair play, while our ranking system matches you with players of similar skill. Dominate the skies and climb the leaderboards!', NULL, false, false, 'approved', false, 1567, 89, 120, 98.5, (SELECT id FROM user_profiles LIMIT 1)),

('Bedrock Elite', 'bedrock.elite-pe.com', NULL, 19132, 25565, 'bedrock', 'survival', 'economy, creative', '1.19', '1.21', 'Philippines', NULL, 'https://discord.gg/bedrockelite', NULL, 'Premium Bedrock Edition experience for mobile and console! Bedrock Elite offers optimized gameplay for all Bedrock platforms with smooth performance and intuitive controls. Our survival world features mobile-friendly interfaces, console-optimized menus, and cross-platform compatibility. Perfect for gaming on any device with friends across all platforms!', NULL, false, false, 'approved', false, 1234, 67, 120, 98.9, (SELECT id FROM user_profiles LIMIT 1)),

('Cross Platform Pro', 'crossplatform.pro-mc.org', 25565, 19132, 25565, 'crossplatform', 'survival', 'economy, towny, creative', '1.19', '1.21', 'Indonesia', 'https://crossplatformpro.org', 'https://discord.gg/crossplatformpro', 'https://youtube.com/crossplatformpro', 'The ultimate cross-platform Minecraft experience! Cross Platform Pro seamlessly connects Java and Bedrock players in one unified world. Our advanced technology ensures feature parity across all platforms while maintaining optimal performance. Build together, trade together, and adventure together regardless of your device. True cross-platform gaming at its finest!', NULL, false, true, 'approved', false, 2678, 134, 200, 99.4, (SELECT id FROM user_profiles LIMIT 1)),

-- Final servers to reach 50
('Test Network', 'test.network-mc.com', 25565, 19132, 25565, 'crossplatform', 'minigames', 'pvp, survival, creative', '1.18', '1.21', 'Bangladesh', NULL, 'https://discord.gg/testnetwork', NULL, 'A comprehensive test network featuring all major gamemodes! Test Network provides a testing ground for new features, plugins, and gameplay mechanics. Our server features experimental game modes, beta testing opportunities, and community feedback systems. Help shape the future of Minecraft servers by testing new features and providing valuable feedback to developers!', 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg', false, false, 'approved', false, 1890, 95, 150, 98.1, (SELECT id FROM user_profiles LIMIT 1)),

('Final Frontier', 'final.frontier-mc.net', 25565, NULL, 25565, 'java', 'survival', 'space, economy, adventure', '1.19', '1.21', 'Chile', 'https://finalfrontier.net', 'https://discord.gg/finalfrontier', 'https://youtube.com/finalfrontier', 'Explore the cosmos in this space-themed survival server! Final Frontier features custom planets, space travel, and alien encounters. Build space stations, explore distant worlds, and establish colonies across the galaxy. Our custom resource system includes rare space materials and alien technologies. With realistic space physics and interplanetary economy, the universe is your playground. The final frontier awaits exploration!', NULL, false, false, 'approved', false, 2456, 123, 180, 99.0, (SELECT id FROM user_profiles LIMIT 1));

-- Update server slugs (this will be handled automatically by the trigger)
-- The trigger_update_server_slug trigger will generate slugs for all new servers